### ISSUE TITLE
Ankidown won't start/crashes directly after installation

### ISSUE THREAD

**Issue by johannesrave** [glfharris/ankidown#17]
When trying to start Ankidown by clicking on 'Tools'->'Ankidown'->'Import' immediatly after installing and restarting Anki I get the following:

```
Error 
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed. 
If the issue only occurs when add-ons are enabled, please use the Tools>Add-ons menu item to disable some add-ons and restart Anki, repeat until you discover the add-on that is causing the problem. 
When you've discovered the add-on that is causing the problem, please report the issue on the add-ons section of our support site. 
Debug info:
Anki 2.1.48 (fb07bad3) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-10-14 10:36:31

Caught exception:
Traceback (most recent call last):
  File "C:\Users\<USER>\AppData\Roaming\Anki2\addons21\38786043\__init__.py", line 11, in open_importer
    aqt.dialogs.open("Ankidown-Importer", mw)
  File "aqt\__init__.py", line 116, in open
  File "C:\Users\<USER>\AppData\Roaming\Anki2\addons21\38786043\importer.py", line 43, in __init__
    self.setupChoosers()
AttributeError: 'AnkidownImporter' object has no attribute 'setupChoosers'
```

EDIT:
It appears that setupChoosers() is now setup_choosers() and works slightly differently? Trying to figure it out, but might just downgrade Anki.

**Comment by mburnett8** [comment]
Here's the [commit](https://github.com/ankitects/anki/commit/ce243c2cae8dec30c88ef7e70851dd8ef2fe2a98) where it changed.
